name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Zip dist folder
      run: zip -r "$(npm pkg get version | tr -d '"').zip" dist
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt